name: Bug Report
description: File a bug report
title: "🪲 Bug: "
labels: ["bug", "help wanted"]
assignees:
  - CrazyH2
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: hack
    attributes:
      label: Hacks used
      description: What hacks were you using when the issue happened
      placeholder: ex. Global/Get All Blooks.js
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what you see in the page
      placeholder: Tell us what you see
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chromium based
        - Safari
        - Opera / (GX)
        - Firefox
        - Other
    validations:
      required: true
  - type: input
    id: otherbrowser
    attributes:
      label: Browser
      description: If you answered Other to the previous question, please extend.
      placeholder: Mosaic
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant console errors
      description: Please copy and paste any  console output. This will be automatically formatted into code, so no need for backticks.
      render: JavaScript
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
